table dCalendario
	lineageTag: 39c69b70-3895-43fd-b649-8df9a5c80318
	dataCategory: Time

	column 'Data.Pedido'
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: b597f116-1d30-42c1-ac74-ac91bd973a94
		summarizeBy: none
		sourceColumn: Data.Pedido

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: becbd60d-7419-4753-a335-67abe67073dc
		summarizeBy: none
		sourceColumn: Ano

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 5e624ea7-ff32-4651-899b-5dd2db66c303
		summarizeBy: none
		sourceColumn: Mês

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Nome do Mês'
		dataType: string
		lineageTag: d31b81ab-6a34-476f-9984-66f4417ca9ac
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: Mês

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 0509e58f-c4f0-41c2-aecc-2d0f6cda37ea
		summarizeBy: none
		sourceColumn: Trimestre

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 9e74d89d-3074-4569-9571-bddc22a23d48
		summarizeBy: none
		sourceColumn: Semana do Ano

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Nome do Dia'
		dataType: string
		lineageTag: 5eb0944c-8aaf-475b-b04d-18c408ff1f5f
		summarizeBy: none
		sourceColumn: Nome do Dia
		sortByColumn: 'Dia da Semana'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana' = WEEKDAY(dCalendario[Data.Pedido])
		formatString: 0
		lineageTag: c6d505fe-eac0-4195-8f9e-38f6147f1fec
		summarizeBy: none

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	hierarchy 'Data.Pedido Hierarquia'
		lineageTag: 6bd5395e-f86b-49ae-9e99-1a5a8515ac7e

		level 'Data.Pedido'
			lineageTag: c1bf32c2-00c1-4cbc-b620-59dd91548903
			column: 'Data.Pedido'

		level Ano
			lineageTag: ab1f4e42-ded7-4fc2-b60b-9ff4f8e53410
			column: Ano

		level Trimestre
			lineageTag: ddf4b24f-9f7c-411e-a018-9b409ab9084e
			column: Trimestre

		level Mês
			lineageTag: f14b5d7d-3f7b-426b-a6f9-23327619188e
			column: Mês

		level 'Nome do Mês'
			lineageTag: 0dcdfca2-3e58-42de-8472-a8f4fa6628a1
			column: 'Nome do Mês'

		level 'Dia da Semana'
			lineageTag: 89f43a18-727e-476d-acf5-93719eff19a8
			column: 'Dia da Semana'

		level 'Nome do Dia'
			lineageTag: 8f166b29-4a4a-4873-bbd5-73bbf69d38be
			column: 'Nome do Dia'

	partition dCalendario = m
		mode: import
		source =
				let
				    DataInicial = Date.StartOfYear(List.Min(fVendas[Data.Pedido])),
				    DataFinal = Date.EndOfYear(List.Max(fVendas[Data.Pedido])),
				    QtdeDias = Duration.Days(DataFinal - DataInicial) + 1,
				    ListaDatas = List.Dates(DataInicial, QtdeDias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data.Pedido"}}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data.Pedido]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data.Pedido]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.ToText([Data.Pedido], "MMM", "pt-BR"), type text),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Nome do Mês Inserido",{{"Nome do Mês", Text.Proper, type text}}),
				    #"Trimestre Inserido" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "Trimestre", each Date.QuarterOfYear([Data.Pedido]), Int64.Type),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Data.Pedido]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Nome do Dia", each Date.ToText([Data.Pedido], "dddd", "pt-BR"), type text),
				    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Nome do Dia Inserido",{{"Nome do Dia", Text.Proper, type text}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colocar Cada Palavra Em Maiúscula1",{{"Data.Pedido", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

