table dCalendario
	lineageTag: 39c69b70-3895-43fd-b649-8df9a5c80318

	column 'Data.Pedido'
		dataType: string
		lineageTag: b597f116-1d30-42c1-ac74-ac91bd973a94
		summarizeBy: none
		sourceColumn: Data.Pedido

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: becbd60d-7419-4753-a335-67abe67073dc
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 5e624ea7-ff32-4651-899b-5dd2db66c303
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: d31b81ab-6a34-476f-9984-66f4417ca9ac
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 0509e58f-c4f0-41c2-aecc-2d0f6cda37ea
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 9e74d89d-3074-4569-9571-bddc22a23d48
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 5eb0944c-8aaf-475b-b04d-18c408ff1f5f
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    DataInicial = Date.StartOfYear(List.Min(fVendas[Data.Pedido])),
				    DataFinal = Date.EndOfYear(List.Max(fVendas[Data.Pedido])),
				    QtdeDias = Duration.Days(DataFinal - DataInicial) + 1,
				    ListaDatas = List.Dates(DataInicial, QtdeDias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data.Pedido"}}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data.Pedido]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data.Pedido]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.ToText([Data.Pedido], "MMMM", "pt-BR"), type text),
				    #"Primeiros caracteres extraídos" = Table.TransformColumns(#"Nome do Mês Inserido", {{"Nome do Mês", each Text.Start(_, 3), type text}}),
				    #"Trimestre Inserido" = Table.AddColumn(#"Primeiros caracteres extraídos", "Trimestre", each Date.QuarterOfYear([Data.Pedido]), Int64.Type),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Data.Pedido]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Nome do Dia", each Date.DayOfWeekName([Data.Pedido]), type text),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.AddColumn(#"Semana do Ano Inserida", "Nome do Dia", each Date.ToText([Data.Pedido], "dddd", "pt-BR"), type text),
				    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Colocar Cada Palavra Em Maiúscula",{{"Nome do Mês", Text.Proper, type text}, {"Nome do Dia", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

