table Medidas
	lineageTag: 3d852403-2716-45ce-b1e1-f973c3b531ad

	measure SomaFrete = SUM(fVendas[Vl.Frete])
		lineageTag: b4938366-5fac-4d20-99c0-139ce2413dee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Faturamento = SUM(fVendas[Vl.Total])
		lineageTag: 414ec12b-729d-44e4-9b47-f5bad8c624f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Meta = SUM(fMetas[Vl.Meta])
		formatString: #,0.00
		lineageTag: 6fb35f6b-1a10-4fea-a4c8-d0ee014a5452

	measure '% Vendas Meta' = [Faturamento] / [Meta]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 58a2c7b3-0ba2-4f81-bdcf-e516b580970e

	measure 'Var Meta' = [% Vendas Meta] - 1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 890c55b0-461f-4783-9d10-1479c1ab4d09

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

